[default]
JWT_SECRET = ""
ALGORITHM = ""
DATABASE_URL = ""

[production]
JWT_SECRET = ""
DATABASE_URL = ""

[development]
JWT_SECRET = ""
DATABASE_URL = ""

[testing]
JWT_SECRET = ""
DATABASE_URL = ""